site_name: Duke's Study notes
repo_url: https://github.com/dukehug/mkdocs_dknotes
repo_name: dukehug/mkdocs_dknotes
site_author: DukeHsu
site_description: dukes study notes on adamson unievrsity - Information Technology
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
  #  - navigation.expand
    - navigation.top
    - navigation.footer
    - toc.follow

    - search.highlight
    - search.share
    - search.suggest

    - content.code.copy
    - content.tabs.link
  palette:
    # 淺色模式設定
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # 深色模式設定 (預設開啟)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
    - search
    - mermaid2
    - glightbox
    - inline-svg
markdown_extensions:
  - admonition
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - meta
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
